trigger:
  branches:
    include:
    - master
  paths:
    exclude: 
    - 'README.md'
    - '*.png'
    - '*.txt'
    - '**\azure?pipelines.yml'

pool:
  name: Hosted VS2017
  demands:
  - msbuild
  - visualstudio
  - vstest

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.4.1'
  inputs:
    versionSpec: 4.4.1

#- task: NuGetCommand@2
#  displayName: 'NuGet restore'
#  inputs:
#    restoreSolution: '**\*.sln'

# .NET Core
# Restore NuGet packages.
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    #verbosityRestore: 'detailed' # Options: quiet, minimal, normal, detailed, diagnostic

- task: VSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: '**\*.sln'
    platform: 'Any CPU'
    configuration: 'Debug'
    maximumCpuCount: true

- task: VSTest@2
  displayName: 'Test Assemblies'
  inputs:
    testAssemblyVer2: |
     **\*test*(s).dll
     !**\obj\**
     !**\xunit.runner.visualstudio.testadapter.dll
     !**\xunit.runner.visualstudio.dotnetcore.testadapter.dll
    runInParallel: true
    runTestsInIsolation: false
    codeCoverageEnabled: true
    platform: 'Any CPU'
    configuration: 'Debug'
    publishRunAttachments: false


# Build source, tests and run tests with coverage
- script: |
    dotnet test ./LoggerLite.xTest/LoggerLite.xTest.csproj -c Debug --logger trx /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  displayName: 'Build source, tests and run tests with coverage'

# Upload coverage to codecov.io
- script: |
    %USERPROFILE%\.nuget\packages\codecov\1.3.0\tools\codecov.exe -f "./LoggerLite.xTest/coverage.opencover.xml" -t $(CODECOV_TOKEN)
  displayName: Upload coverage to codecov.io
failOnStderr: false