
trigger:
  branches:
    include:
    - master
  paths:
    exclude: 
    - 'README.md'
    - '*.png'
    - '*.txt'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


- task: VSTest@2
  displayName: 'Test Assemblies'
  inputs:
    testAssemblyVer2: |
     **\*test*(s).dll
     !**\obj\**
    runInParallel: true
    runTestsInIsolation: true
    codeCoverageEnabled: true
    platform: $(BuildPlatform)
    configuration: $(BuildConfiguration)
