
trigger:
  branches:
    include:
    - master
  paths:
    exclude: 
    - 'README.md'
    - '*.png'
    - '*.txt'

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- script: dotnet test  --no-build --list-tests --verbosity normal
  displayName: 'dotnet test'
